#!/usr/bin/env bash
# Installs (or removes, with --remove) the Windows-logon autostart for the
# vel'OH collector, and starts the collector right away.
#
# WSL cannot boot itself when Windows starts, so a tiny generated launcher is
# dropped into the Windows Startup folder; at every logon it boots this distro
# and runs collector/run-local.sh without opening a console window. The
# launcher is a generated artifact (not tracked in git) — all maintained
# logic lives in bash.
#
# Usage (inside WSL):
#   collector/install-autostart.sh           # install + start now
#   collector/install-autostart.sh --remove  # uninstall + stop collector
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
distro="${WSL_DISTRO_NAME:?must run inside WSL}"
startup_win="$(powershell.exe -NoProfile -Command "[Environment]::GetFolderPath('Startup')" | tr -d '\r')"
startup="$(wslpath "$startup_win")"
target="$startup/veloh-collect-wsl.vbs"

if [[ "${1:-}" == "--remove" ]]; then
  rm -f "$target"
  pkill -f 'collect.mjs --loop' 2>/dev/null || true
  echo "autostart removed, collector stopped"
  exit 0
fi

cat > "$target" <<EOF
' Generated by collector/install-autostart.sh — do not edit, reinstall instead.
Set sh = CreateObject("WScript.Shell")
sh.Run "wsl.exe -d $distro -u $USER -- $here/run-local.sh", 0, False
EOF
echo "installed: $target"

nohup "$here/run-local.sh" >/dev/null 2>&1 &
disown
sleep 1
echo "collector: $(pgrep -af 'collect.mjs --loop' || echo 'FAILED TO START')"
